spring.application.name=movie

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.flyway.enabled=false

logging.level.org.springframework.web=DEBUG
logging.level.com.example.movie=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=ALWAYS
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
