spring:
  application:
    name: movie
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:classpath:application-secret.yml
  flyway:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: ALWAYS
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: DEBUG
    com.example.movie: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

vnpay:
  tmnCode: ${VNPAY_TMN_CODE:DEMO_TMN}
  hashSecret: ${VNPAY_HASH_SECRET:DEMO_SECRET}
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payments/vnpay-return

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

server:
  port: 8080
  forward-headers-strategy: framework

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-afd9d79-namanhdang0905-942b.f.aivencloud.com:15505/defaultdb?ssl-mode=REQUIRED}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

vnpay:
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://movie-be-hecl.onrender.com/api/payments/vnpay-return

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  forward-headers-strategy: framework